### ISSUE TITLE
QRCodeService not work in 2020 onward Unity Version 

### ISSUE THREAD

**Issue by Dhruvi05IF** [LocalJoost/QRCodeService#10]
![MRTKIssue](https://user-images.githubusercontent.com/103554104/174578376-1370809e-fbf2-401c-9045-3f7cdec6f8f1.JPG)
hello sir,

please help me to provide a solution for bellow issue.

QRCodeService gives an error when try to upgrade the project in 2020.3.7 unity version. i will also installed Mixed Reality OpenXR Plugin using mixed reality feature toolkit.

issue is --> Assets\MRTKExtensions\QRCodes\SpatialGraphCoordinateSystemSetter.cs(20,17): error CS0246: The type or namespace name 'PositionalLocatorState' could not be found (are you missing a using directive or an assembly reference?)

**Comment by LocalJoost** [comment]
Unity 2020 and up require a plugin structure that is not supported by the code you use. Read https://localjoost.github.io/Upgrading-reading-and-positioning-QR-codes-with-HoloLens-2-to-Unity-2020-+-OpenXR-plugin/ and pull branch https://github.com/LocalJoost/QRCodeService/tree/openxr

**Comment by Dhruvi05IF** [comment]
Thank you sir for your reply
