### ISSUE TITLE
unable to read qrcodes

### ISSUE THREAD

**Issue by Salsa852** [LocalJoost/QRCodeService#13]
Hello ,
thank you for this project.
I already tested the project on the main branch with unity 2019 , 3 months ago and everything works fine.
I tried to retest yesterday and there is a problem with the tracking for the two scenes (it manages to detect the qr code and display the plane but it displays nothing on the debug window nor the qr code information ( I tested the main , change package , bloc1 branches)
it sems like the information are not uploaded
![20220708_010753_HoloLens](https://user-images.githubusercontent.com/45318931/177953504-2834dc81-7997-4d7e-8b21-67c6dda431cb.jpg)

**Comment by LocalJoost** [comment]
Listen, I like to help. But you said it worked before, and now it doesn't. So I would suggest checking out what you did different this time first. You give me virtually no information at all ;). Please read all the blogs I wrote about it, for the various branches. Thank you
