### ISSUE TITLE
Problem while launching app

### ISSUE THREAD

**Issue by ManChrys** [LocalJoost/QRCodeService#14]
Hello,

when I'm launching the app on holo2 I give all permissions and after that I can only see this.

![file](https://user-images.githubusercontent.com/67521662/178916793-440d1dcf-f235-4c39-97c0-693464c55ea6.jpg)

its unity's environment

![22222](https://user-images.githubusercontent.com/67521662/178917026-d7c0ae73-d115-4910-b662-fed454a3fdb2.jpg)

That means that holo's camera don't get triggered ? I followed your blog's instructions.

Thanks in advance.

**Comment by LocalJoost** [comment]
Hi, this might surprise you, but based upon screen shots and no errors I really can't fathom what you might have done wrong. Did you read all the instructions at the end of https://localjoost.github.io/Positioning-QR-codes-in-space-with-HoloLens-2-building-a-'poor-man's-Vuforia'/ ? Did you try to download the fully built app and deploy it? What scenes were in your build? SampleScene or SampleScene2?. Etc

**Comment by ManChrys** [comment]
Hi,
Thanks for the fast response. I build it again with "slightly improved" branch and I updated to unity 2020 and worked fine. I would like to ask where can I find the QR code you use, so I can spawn the plane ? 

Thanks in advance.

**Comment by ManChrys** [comment]
ok i found it . Have a nice day.
