### ISSUE TITLE
How to merge a local coordinate system in your project? 

### ISSUE THREAD

**Issue by CiEud** [LocalJoost/QRCodeService#15]
Hello! 
first of all thank you very much for your project. It works perfectly. 
I am a beginner in programming for HoloLens 2, so my question is probably not directly for your project, but maybe you can help me. 
The plane appears on the center of the QR code, but I want to use this QR code as an orientation to connect a local coordinate system in my space, for example from a robotic system, to the coordinate system of HoloLens2. So that the origins are the same and I can display a hologram on the Hololens with the coordinates from the robotic system. I don't know where in your project to access the coordinates and how to merge the systems.

**Comment by LocalJoost** [comment]
Hi, I really have no idea, as I have no idea what kind your system might use. HoloLens basically defines 0,0,0 as the place where it was when it started the app, and "forward" as de direction in the horizontal plane it was rotated at that same moment. Maybe the coordinates you need are the coordinates and rotation of the airplane (or the QR code marker) itself? If you know that that should be according to your own coordinate system, you might do some translation math. How that should work, no idea
