### ISSUE TITLE
The first web link in the README file is wrong.

### ISSUE THREAD

**Issue by Hanning-Liu** [LocalJoost/QRCodeService#18]
It should be
https://localjoost.github.io/Reading-QR-codes-with-an-MRTK2-Extension-Service/ 
rather than
https://localjoost.github.io/Reading-QR-codes-with-an-MRTK2-Extension-Service/'/

**Comment by Hanning-Liu** [comment]
The one under blog1 branch!

**Comment by LocalJoost** [comment]
Yeah Yeah I know. I adapted a few more. Thanks
