### ISSUE TITLE
No QR codes being read

### ISSUE THREAD

**Issue by aswad546** [LocalJoost/QRCodeService#20]
Hello,

I am attempting to use your demo QR code example that reads multiple QR codes and anchors objects to them as per your blog (https://localjoost.github.io/Showing-multiple-location-based-items-based-on-QR-codes-using-MRTK3-and-HoloLens-2/). I am relatively new to HoloLens development. I used the recommended version of Unity 2021.3.23f1 and all the other configurations mentioned in the MRTK3MultiQR branch. The code builds correctly but it does not show anything as UI on the HoloLens 2, the app just opens and shows nothing. I try to read QR codes, I also generated codes that link to https://localjoost.github.io but still the app shows nothing. Could please point me in the right direction?

Thank you

**Comment by LocalJoost** [comment]
Hi @aswad546,

You are mixing things up. The link to https://localjoost.github.io/ is for the single QR code sample. As you can read here https://localjoost.github.io/Showing-multiple-location-based-items-based-on-QR-codes-using-MRTK3-and-HoloLens-2/#tracker you can see it looks for a QR code with "HLItem1". As you can see in the editor, on the other trackers, the other two are "HLItem2" and "HLItem3".

**Comment by aswad546** [comment]
Thanks so much for your prompt response, that did the trick. I'm sorry I must have missed that
