### ISSUE TITLE
app won't read Qr codes on second launch

### ISSUE THREAD

**Issue by MattLsc** [LocalJoost/QRCodeService#21]
Hello, 
First of all, thanks for the code and the explanation on you blog it's really helpful for beginners like me :)

I'm having a problem using the MRTK3 project.
It's building fine and it's working perfectly on the first launch (the one where it's asking for permissions) but after i close the app or turn off the hololens 2 and try to launch it again it seems unable to read the Qr code again. 
I checked and the app still have the permissions to use the camera, it seems to be running correctly (I can press the reset button) but still it doesn't read the Qr code.

Any suggestion on how to fix this problem ? Thanks a lot!

**Comment by LocalJoost** [comment]
Mmm. Not sure. What do you mean with "turn off" or "close the app". If you just leave it, for the home menu, it might stay active and not properly initialize anymore. What branch have you been using? There are quite some variants now, see.

**Comment by MattLsc** [comment]
I leave for the menu and close the tab that is popping up. 
I also tried turning off the hololens and turning it back on, still not working :/
I'm using the MRTK3 project .zip

**Comment by LocalJoost** [comment]
> I'm using the MRTK3 project .zip

You mean you are downloading this branch?
![image](https://github.com/LocalJoost/QRCodeService/assets/4129183/ee359e51-aace-4cf4-92c6-7b0f7a486ce2)

> I leave for the menu and close the tab that is popping up.

You mean, you go to the HoloLens home menu using the wrist menu and close the window that says "QRCodeService" ?

> I also tried turning off the hololens and turning it back on, still not working :/

So it ran once, and never, ever again? You know just pressing the off and on buttons does not really turn off the HoloLens, just puts it to sleep?

Please work with me, don't let me guess what you are doing or assume I am some godlike being with telepathic abilities. I wish I was :D

**Comment by MattLsc** [comment]
So i managed to make it work,

I used the debug logger and saw that it was detecting the Qr code but it was not creating the marker.
I printed a bigger Qr code (10x10cm) instead of (7x7cm) and i don't know how (probably forbidden magic and a lot of builds), it worked just fine.

I can't say for sure where the real problem was but working with your code will allow me to further understand it and maybe i'll come back with the solution another time :)

Thanks again!!

**Comment by LocalJoost** [comment]
@MattLsc ah yes... In this article https://localjoost.github.io/Positioning-QR-codes-in-space-with-HoloLens-2-building-a-'poor-man's-Vuforia'/ there's a video in which I try various sizes. 10x10 is almost instant success - 9cm works also okay, below that the success rate rapidly drops off. Glad you were able to fix it it yourself. Have fun and good luck!
