### ISSUE TITLE
Locate and mark multiple QR codes at the same time

### ISSUE THREAD

**Issue by Ryxuu** [LocalJoost/QRCodeService#4]
Hello!

What do you think, is it possible to locate and mark multiple QR-codes at the same time? I mean the following:

We have two QR-codes: one with matching value and other with non-matching value. I would like to achieve that to mark the matched code with green and the non-matched code with red at the same time.

Is this implementation capable for this purpose?

Thank you!

**Comment by LocalJoost** [comment]
Hi!

The HoloLens and the library are definitely able to recognize multiple QR codes. If the codes arrive at exactly the same time, I don't know, but probably close to each other. You will need to change the code I wrote quite a bit, but it's certainly doable.
