### ISSUE TITLE
 The type or namespace name 'PositionalLocatorState' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by shoukailiang** [LocalJoost/QRCodeService#7]
Hello,  @LocalJoost .it is a great project.
 the unity version is : 2020.3.18
When I cloned the openxr branch, I found that there were some problems
![image](https://user-images.githubusercontent.com/24668909/132977704-aa7b92d9-e463-420f-bcef-3106c27eb587.png)

**Comment by LocalJoost** [comment]
Hi @shoukailiang I have done the following:

- Downloaded the project from GitHub
- Switched to the openxr branch
- Opened the project in Unity **2020.3.7.f1** : no errors
- Switched to Universal Windows Platform in Build Settings : still no errors
- Entered playmode: no errrors
- Built the C++ solution: no errors.

So I don't know what your problems might be. Things you might try checking:

- Do you have UWP support installed?
- Do you have NuGet for Unity installed?
- Can you open the main branch using the Unity 2019 editor (don't know the exact version I used, I think 2019.4.20f1)

**Comment by shoukailiang** [comment]
Thank you for your reply. I did miss something

**Comment by shoukailiang** [comment]
Thank you for your reply @LocalJoost .I did miss something.
