### ISSUE TITLE
MRTK Update

### ISSUE THREAD

**Issue by Bastien1612** [LocalJoost/QRCodeService#8]
Hello,

I tried to update the MRTK by importing with unitypackage they give on their repository but everything start to errors.
Is it possible to update the MRTK with this project? And if yes, how?

**Comment by LocalJoost** [comment]
Can you give a little more context?

- What branch did you pull?
- What version of Unity do you use?
- How did you update the MRKT? Did you use the feature tool?
- What else did you change?
- Did you read the blog posts that go with this project?

Suppose you are me. You have written a blog post like mine, and published a little sample project. The sentences you wrote is all you get to go by. Would you know how to give an answer, of even have the remotest clue of what could possibly go wrong?

**Comment by Bastien1612** [comment]
I pull the main Branch.
My Unity version is 2019.4.30.
I try to update to 2.6.1, to update like I said I use the unitypackage like the picture below : 
![image](https://user-images.githubusercontent.com/33509681/149281045-86bc8a65-a504-48a9-9a2e-f8548aa59faf.png)
I change nothing else.

**Comment by LocalJoost** [comment]
Not sure what is happening here and I need to try to repro what is going wrong. I did upgrade to 2.6.1 in this branch https://github.com/LocalJoost/QRCodeService/tree/openxr/ but that uses Unity 2020.3.7 and the packages are loaded using the MRKT Feature tool. This is the openXR version. Currently I am at work and don't have time to check what is going wrong.

**Comment by LocalJoost** [comment]
After finishing my working day, I tried to upgrade the main branch. So here's what I did

- I cloned the main branch fresh from github
- I opened the project in Unity (2019.4.17f1)
- In build settings, I set the platform to Universal Windows Platform. This is a HoloLens 2 app after all.
- Using the Package manager, I removed all the Mixed Reality Toolkit packages
- Then I opened the Mixed Reality Toolkit feature tool and added the newest MRKT to the project (2.7.3):

![image](https://user-images.githubusercontent.com/4129183/149383088-8652ad91-914f-4c40-90ad-db5048bbbffd.png)

And I got ZERO errors. 

I suggest abandoning the Package Manager and using the MRKT Feature Tool. If you check the OpenXR branch, you can see this working already under Unity 2020, which I would very much recommend for new projects.

**Comment by Bastien1612** [comment]
Sorry for this late answer I was on many subject.

I tried what you said and I don't have the last error I had in console, but when I try to build appx with the build window :

![image](https://user-images.githubusercontent.com/33509681/152009012-ff086c8f-ae1d-4799-9521-45c1c2c2d8b4.png)

I tried also the OpenXR branch and it works well.

**Comment by LocalJoost** [comment]
But that's a _warning_. Not an error.

**Comment by Bastien1612** [comment]
There is 1 warning ("1 Avertissement(s)" on the screenshot) and 1 error ("1 Erreur(s)" on the screenshot) and the appPackage folder is not build.

**Comment by LocalJoost** [comment]
A build error is proceeded by a red bang. You only show information logs. See this? From your screen shots? 
![image](https://user-images.githubusercontent.com/4129183/152034308-87c923a2-e793-411d-9200-1e4d704e0e09.png)
115 informational logs, 6 warnings, 0 errors. 
The Appx should not be built from Unity: Unity should generate a Visual C++ solution you should deploy using Visual C++
I really have no idea what you are doing and how. You give me so little, and I am not clairvoyant. Did you ever make, build and deploy a HoloLens apps before?
