### ISSUE TITLE
Unable to Read QRcode

### ISSUE THREAD

**Issue by hakyung9712** [LocalJoost/QRCodeService#9]
Hi, I want to try reading QRcode with your code. But I have some problems.

Before showing the situation, I get the code from your "openxr" branch.
And print QRcode in your blog. When I turn off the app, the green box shows above the QRcode.

When I build the Scene1, the text don't change after the "Initializing QR tracker attempt 1".
And when I build the Scene2, the airplane and tracker shows, but the QR displayer doesn't show the QRCode information like link .. or something.

I am trying to this so much time and I really want your help... Thanks
![20220221_141826_HoloLens](https://user-images.githubusercontent.com/47092708/154894546-20f06ab8-0580-4f07-8759-d7018c1fc307.jpg)
![20220221_141300_HoloLens](https://user-images.githubusercontent.com/47092708/154894557-66d44c0d-05d6-45d0-9c89-47dd1479d978.jpg)

**Comment by LocalJoost** [comment]
Hello!
I just built the app with Scene 1 and deployed, and it worked fine: 
![image](https://user-images.githubusercontent.com/4129183/155011887-682e753c-dc40-4ba5-a64c-b3b4a50483c0.png)

What you might need to do is move the QR code a bit closer to your head, a bit further away, and look at it from a straight angle. Also, I have found out that the smaller the QR code, the harder it is to recognize for the HoloLens. Finally, remember the HoloLens cameras are basically sitting _on your forehead_. So if you hold the code before your _eyes_, you might be holding them too low.

Good luck. I am sure it works. The fact you can show the airplane proves it.

**Comment by Patsufr** [comment]
Hi, i have the same problem. When i try to detect your Qr this happening with visual studio : 
![image](https://user-images.githubusercontent.com/39172887/156132383-3e4dd3d2-427d-4dff-aad1-dc9fedef3a43.png)
When I try without visual studio nothing happens like hakyung9712. Do you have any ideas ? 
Thanks you.

**Comment by LocalJoost** [comment]
- What branch did you pull?
- What version of Unity do you use?
- Did you build for Master?

I can tell you, running from Visual Studio does not make any sense. You are now debugging a generated C++ application. 

If deploy and build Scene 1, I get this:
![image](https://user-images.githubusercontent.com/4129183/156135216-21ae1af6-5d0d-4931-a33d-7d679bcd6d13.png)
If I deploy and build Scene 2, I get this:
https://user-images.githubusercontent.com/47092708/154894557-66d44c0d-05d6-45d0-9c89-47dd1479d978.jpg

From what you send me I can tell nothing

**Comment by Patsufr** [comment]
I tried your main branch and your blog1 branch.
I used 2019.4.34f1
I build for release.

Thank you about Visual Studio i'm beginner in this domain.

**Comment by LocalJoost** [comment]
So the best branch to pull is https://github.com/LocalJoost/QRCodeService/tree/slightly_improved_version

Have you read [my blog post about this? ](https://localjoost.github.io/Positioning-QR-codes-in-space-with-HoloLens-2-building-a-'poor-man's-Vuforia'/#conclusion) and then especially the end. It has _very_ specific build instructions.

- Build with Unity 2019.4.17 LTS or higher 2019 LTS version but not Unity 2020 or 2021
- Make sure you have selected Target SDK and Minimum platform version 18362
- Make sure you have selected Universal Windows Platform
- Make sure you have selected ARM64 and D3D.
- Target Platform versions are set to 18632 or higher
- **Deploy to HoloLens 2 using Visual Studio 2019, platform toolset 142 and build settings Master/ARM64**

**Comment by Patsufr** [comment]
I will try that !
Thanks
I come back to you

**Comment by hakyung9712** [comment]
I found I was using Unity 2020. I will try and come back. Thanks!

Also, I have a question. Can only one QR code be recognized? I found "Local Qr Value" in Qr Tracker Controller.

**Comment by LocalJoost** [comment]
@hakyung9712 If you want to use Unity 2020, pull branch https://github.com/LocalJoost/QRCodeService/tree/openxr and read [this follow up article](https://localjoost.github.io/Upgrading-reading-and-positioning-QR-codes-with-HoloLens-2-to-Unity-2020-+-OpenXR-plugin/)
